name: .NET Core
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:        
    - uses: actions/checkout@v2
    - name: Setup .NET Core in working directory - $working-directory
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101    
#    - name: Install dependencies
#      run: dotnet restore
    - name: Build
      run: dotnet build ./src/Azure.Cognitive.Services.Speech.Samples/Azure.Cognitive.Services.Speech.Samples.sln --configuration Release    
    - name: Test
      run: dotnet test ./src/Azure.Cognitive.Services.Speech.Samples/Azure.Cognitive.Services.Speech.Samples.sln --no-restore --verbosity normal
