name: .NET Core
env:
  solution: './src/Azure.Cognitive.Services.Speech.Samples/Azure.Cognitive.Services.Speech.Samples.sln'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:        
    
    - uses: actions/checkout@v2
      
      if: matrix.os == 'macOS-latest' || matrix.os == 'ubuntu-latest'
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101    

    - name: Build
      run: dotnet build $solution --configuration Release    

    - name: Test
      run: dotnet test $solution --configuration Release --no-restore --verbosity normal
