name: .NET Core
env:
  solution: 'Azure.Cognitive.Services.Speech.Samples.sln'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}    
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:            
    - uses: actions/checkout@v2        
    - name: Setup .NET Core for ${{ matrix.os }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101    
      if: matrix.os == 'macOS-latest' || matrix.os == 'ubuntu-latest'
    - name: Build on ${{ matrix.os }}
      working-directory: './src/Azure.Cognitive.Services.Speech.Samples/'
      run: dotnet build $solution --output ./publish_output --configuration Release  
    - name: Test on ${{ matrix.os }}
      working-directory: './src/Azure.Cognitive.Services.Speech.Samples/'
      run: dotnet test $solution --configuration Release --no-restore --verbosity normal
    - name: Archive files on ${{ matrix.os }}
      uses: actions/upload-artifact@v1
      with: 
        name: dist
        path: './src/Azure.Cognitive.Services.Speech.Samples/publish_output'
    - name: Directory
      run: ls -l './src/Azure.Cognitive.Services.Speech.Samples'
