name: .NET Core
env:
  solution: './src/Azure.Cognitive.Services.Speech.Samples/Azure.Cognitive.Services.Speech.Samples.sln'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:        
    - uses: actions/checkout@v2
    - name: Setup .NET Core in working directory - $working-directory
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101    
    - name: Build
      run: dotnet build $solution --configuration Release    
    - name: Test
      run: dotnet test $solution --no-restore --verbosity normal
